apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RabbitMQHost: ${{ secrets.RabbitMQHost }}
  RabbitMQPort: ${{ secrets.RabbitMQPort }}
  RabbitMQUser: ${{ secrets.RabbitMQUser }}
  RabbitMQPassword: ${{ secrets.RabbitMQPassword }}

# These values should never be exposed, even thought it's a personal project
# running in a Docker Desktop k8s cluster, it's good practice to keep them private
