apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RabbitMQHost: ${{ secrets.RABBITMQ_HOST }}
  RabbitMQPort: ${{ secrets.RABBITMQ_PORT }}
  RabbitMQUser: ${{ secrets.RABBITMQ_USER }}
  RabbitMQPassword: ${{ secrets.RABBITMQ_PASSWORD }}
