apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
type: Opaque
data:
  MktMSConnStr: ${{ secrets.SQLSERVER_CONNSTR }}

# These values should never be exposed, even thought it's a personal project
# running in a Docker Desktop k8s cluster, it's good practice to keep them private
