apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-service
  template:
    metadata:
      labels:
        app: sales-service
    spec:
      containers:
      - name: sales-service
        image: felipehimself/market-sales
        env:
        - name: RabbitMQHost
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RabbitMQHost
        - name: RabbitMQPort
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RabbitMQPort
        - name: RabbitMQUser
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RabbitMQUser
        - name: RabbitMQPassword
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RabbitMQPassword
